# Generated by Django 4.2.18 on 2025-03-06 00:30

from django.db import migrations, models
import tom_eso.models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_eso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esoprofile',
            name='encrypted_p2_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esoprofile',
            name='p2_environment',
            field=models.CharField(choices=[(tom_eso.models.ESOP2Environment['DEMO'], 'demo'), (tom_eso.models.ESOP2Environment['PRODUCTION'], 'production'), (tom_eso.models.ESOP2Environment['PRODUCTION_LASILLA'], 'production_lasilla')], default='demo', max_length=32, verbose_name='Environment'),
        ),
        migrations.AddField(
            model_name='esoprofile',
            name='p2_username',
            field=models.CharField(blank=True, default='520520', max_length=255, null=True, unique=True),
        ),
    ]
