# Generated by Django 4.2.18 on 2025-03-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_eso', '0002_esoprofile_encrypted_p2_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esoprofile',
            old_name='encrypted_p2_password',
            new_name='ciphertext_p2_password',
        ),
        migrations.AlterField(
            model_name='esoprofile',
            name='p2_environment',
            field=models.CharField(choices=[('demo', 'Demo'), ('production', 'Production'), ('production_lasilla', 'Production Lasilla')], default='demo', max_length=32),
        ),
    ]
