# Generated by Django 5.2.14 on 2026-06-13 01:10

import tom_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_eso', '0003_alter_esoprofile_p2_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esoprofile',
            name='_p2_password_encrypted',
        ),
        migrations.AddField(
            model_name='esoprofile',
            name='p2_password',
            field=tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True),
        ),
    ]
