# Generated by Django 4.2.18 on 2025-03-19 01:29

from django.db import migrations
import tom_eso.models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_eso', '0003_rename_encrypted_p2_password_esoprofile_ciphertext_p2_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esoprofile',
            name='ciphertext_p2_password',
        ),
        migrations.AddField(
            model_name='esoprofile',
            name='_ciphertext_p2_password',
            field=tom_eso.models.EncryptedBinaryField(blank=True, null=True),
        ),
    ]
