# Generated by Django 4.2.18 on 2025-04-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_eso', '0004_remove_esoprofile_ciphertext_p2_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esoprofile',
            name='p2_username',
            field=models.CharField(blank=True, default='520520', max_length=255, null=True),
        ),
    ]
